server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache des assets statiques
    location ~* \.(css|js|woff2|png|jpg|ico)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Compression
    gzip on;
    gzip_types text/html text/css application/javascript;
}